export const rentHouses = [
  {
    id: 1,
    type: "featured",
    mainImage: "/Rent-houses/House-1/home1-1.jpg",
    moreImages: [
      "/Rent-houses/House-1/home1-2.jpg",
      "/Rent-houses/House-1/home1-3.jpg",
      "/Rent-houses/House-1/home1-4.jpg",
      "/Rent-houses/House-1/home1-5.jpg",
    ],
    name: "Sangamner",
    address: "Akole Road, Sangamner, Maharashtra",
    price: 45000,
    details: [
      "3 Bedrooms",
      "3 attached Bathrooms",
      "1 common Bathroom",
      "2 Kitchens",
      "Modern design structure",
      "Unfurnished",
      "Prime Location",
      "Area: 1500 sq.ft",
    ],
    description:
      "Beautiful property located in the heart of Sangamner. This spacious home features modern amenities, ample natural light, and is close to schools, markets, and hospitals. Perfect for families looking for a comfortable living space in a peaceful neighborhood.",
  },
  {
    id: 2,
    type: "featured",
    mainImage: "/Rent-houses/House-2/home2-1.jpg",
    moreImages: [
      "/Rent-houses/House-2/home2-2.jpg",
      "/Rent-houses/House-2/home2-3.jpg",
      "/Rent-houses/House-2/home2-4.jpg",
      "/Rent-houses/House-2/home2-5.jpg",
    ],
    name: "Shirdi",
    address: "Nagar-Manmad Highway, Shirdi, Maharashtra",
    price: 55000,
    details: [
      "4 Bedrooms",
      "1 large living room",
      "4 attached Bathrooms",
      "1 common Bathroom",
      "2 Kitchens",
      "Garden with parking space",
      "Semi-furnished",
      "Area: 2000 sq.ft",
    ],
    description:
      "Luxurious property in Shirdi, just 1 km from the Sai Baba Temple. This well-designed home offers spacious rooms, modern amenities, and a serene environment. Ideal for devotees looking for a permanent residence or investors seeking rental opportunities in this popular pilgrimage destination.",
  },
  {
    id: 3,
    type: "popular",
    mainImage: "/Rent-houses/House-3/home3-1.jpg",
    moreImages: [
      "/Rent-houses/House-3/home3-2.jpg",
      "/Rent-houses/House-3/home3-3.jpg",
      "/Rent-houses/House-3/home3-4.jpg",
      "/Rent-houses/House-3/home3-5.jpg",
    ],
    name: "Nashik",
    address: "College Road, Nashik, Maharashtra",
    price: 60000,
    details: [
      "Premium location near College Road",
      "3 Bedrooms",
      "2 Bathrooms",
      "Modern kitchen",
      "Floor Level: 5th floor",
      "Fully furnished",
      "Area: 1200 sq.ft",
    ],
    description:
      "Elegant apartment in the heart of Nashik city. This fully furnished property offers panoramic views, 24/7 security, power backup, and reserved parking. Located in a prime area with easy access to educational institutions, shopping centers, and healthcare facilities.",
  },
  {
    id: 4,
    type: "popular",
    mainImage: "/Rent-houses/House-4/home4-1.jpg",
    moreImages: [
      "/Rent-houses/House-4/home4-2.jpg",
      "/Rent-houses/House-4/home4-3.jpg",
      "/Rent-houses/House-4/home4-4.jpg",
      "/Rent-houses/House-4/home4-5.jpg",
    ],
    name: "Nashik",
    address: "Gangapur Road, Nashik, Maharashtra",
    price: 75000,
    details: [
      "Location: Gangapur Road",
      "4 Bedrooms",
      "Spacious Living Room",
      "3 Bathrooms",
      "2 Modern kitchens",
      "Floor Level: Ground floor",
      "Semi-furnished",
      "Area: 2,200 sq.ft",
    ],
    description:
      "Luxurious bungalow in the upscale Gangapur Road area of Nashik. This property features a beautiful garden, spacious interiors, and high-quality finishes. Perfect for families looking for a premium living experience in one of Nashik's most sought-after neighborhoods.",
  },
  {
    id: 5,
    type: "popular",
    mainImage: "/Rent-houses/House-5/home5-1.jpg",
    moreImages: [
      "/Rent-houses/House-5/home5-2.jpg",
      "/Rent-houses/House-5/home5-3.jpg",
      "/Rent-houses/House-5/home5-4.jpg",
      "/Rent-houses/House-5/home5-5.jpg",
    ],
    name: "Sangamner",
    address: "Ghulewadi Road, Sangamner, Maharashtra",
    price: 40000,
    details: [
      "Residential property in quiet neighborhood",
      "3 Bedrooms",
      "Large living area",
      "3 Bathrooms",
      "Modern kitchen",
      "Unfurnished",
      "Car Parking",
      "Area: 1800 sq.ft",
    ],
    description:
      "Charming property in a peaceful residential area of Sangamner. This home offers a perfect blend of comfort and convenience with spacious rooms, good ventilation, and a well-planned layout. Close to essential amenities and educational institutions, making it ideal for families.",
  },
  {
    id: 6,
    type: "featured",
    mainImage: "/Rent-houses/House-6/home6-1.jpg",
    moreImages: [
      "/Rent-houses/House-6/home6-2.jpg",
      "/Rent-houses/House-6/home6-3.jpg",
      "/Rent-houses/House-6/home6-4.jpg",
      "/Rent-houses/House-6/home6-5.jpg",
    ],
    name: "Shirdi",
    address: "Pimpalwadi Road, Shirdi, Maharashtra",
    price: 65000,
    details: [
      "Premium Villa in Shirdi",
      "5 Bedrooms",
      "Spacious Living Room",
      "5 Bathrooms",
      "2 Modern kitchens",
      "Fully furnished",
      "Covered Car Parking",
      "Area: 2500 sq.ft",
    ],
    description:
      "Exclusive villa in a gated community in Shirdi. This property offers luxury living with high-end finishes, landscaped gardens, and modern amenities. Located in a serene environment yet close to the main attractions of Shirdi, making it perfect for both residential and investment purposes.",
  },
];
