export const maharashtraCities = [
  "Mumbai",
  "Pune",
  "Nagpur",
  "Thane",
  "Nashik",
  "Aurangabad",
  "Solapur",
  "Kolhapur",
  "Amravati",
  "Nanded",
  "Sangli",
  "Latur",
  "Dhule",
  "Ahmednagar",
  "Akola",
  "Jalgaon",
  "Chandrapur",
  "Parbhani",
  "Jalna",
  "Bhiwandi",
  "Panvel",
  "Satara",
  "Beed",
  "Yavatmal",
  "Osmanabad",
  "Nandurbar",
  "Wardha",
  "Hingoli",
  "Washim",
  "Gadchiroli"
];

// Sample property descriptions for Maharashtra cities
export const cityDescriptions = {
  "Mumbai": "Financial capital of India with beautiful sea-facing properties and vibrant urban lifestyle.",
  "Pune": "Educational hub with pleasant climate and growing IT sector, offering modern amenities.",
  "Nagpur": "Orange city with spacious properties and excellent connectivity to major cities.",
  "Thane": "Suburban area near Mumbai with lush greenery and modern residential complexes.",
  "Nashik": "Wine capital of India with scenic landscapes and religious significance.",
  "Aurangabad": "Historical city with rich cultural heritage and growing industrial sector.",
  "Solapur": "Textile hub with affordable housing options and developing infrastructure.",
  "Kolhapur": "Known for its rich history, cuisine, and beautiful surroundings.",
  "Amravati": "City with historical significance and developing real estate market.",
  "Nanded": "Religious city with peaceful neighborhoods and growing infrastructure.",
  "Sangli": "Agricultural hub with spacious properties and peaceful environment.",
  "Latur": "Emerging city with educational institutions and affordable housing.",
  "Dhule": "Industrial city with growing residential areas and good connectivity.",
  "Ahmednagar": "Historical city with peaceful residential areas and moderate climate.",
  "Akola": "Cotton city with affordable housing options and developing infrastructure.",
  "Jalgaon": "Known for banana cultivation with growing residential areas.",
  "Chandrapur": "Industrial city with spacious properties and natural surroundings.",
  "Parbhani": "Agricultural city with peaceful neighborhoods and affordable housing.",
  "Jalna": "Industrial city with growing residential market and good connectivity.",
  "Bhiwandi": "Textile hub near Mumbai with affordable housing options.",
  "Panvel": "Rapidly developing city near Mumbai with modern infrastructure.",
  "Satara": "Hill station city with beautiful views and pleasant climate.",
  "Beed": "Agricultural district with peaceful residential areas and affordable housing.",
  "Yavatmal": "Cotton city with growing infrastructure and educational institutions.",
  "Osmanabad": "Historical city with peaceful neighborhoods and affordable properties.",
  "Nandurbar": "Tribal district with natural beauty and developing infrastructure.",
  "Wardha": "Historical significance with peaceful residential areas and educational institutions.",
  "Hingoli": "Agricultural district with affordable housing and peaceful environment.",
  "Washim": "Growing city with affordable housing options and agricultural surroundings.",
  "Gadchiroli": "Forest district with natural beauty and developing infrastructure."
}; 