export const maharashtraCities = [
  "Mumbai",
  "Pune",
  "Nagpur",
  "Thane",
  "Nashik",
  "Aurangabad",
  "Solapur",
  "Amravati",
  "Kolhapur",
  "Navi Mumbai",
  "Sangli",
  "Satara",
  "Latur",
  "Dhule",
  "Ahmednagar",
  "Akola",
  "Jalgaon",
  "Chandrapur",
  "Parbhani",
  "Jalna",
  "Bhiwandi",
  "Nanded",
  "Alibaug",
  "Lonavala",
  "Mahabaleshwar",
  "Panchgani",
  "Matheran",
  "Ratnagiri",
  "Sindhudurg",
  "Shirdi"
];

export const cityDescriptions = {
  "Mumbai": "The financial capital of India, Mumbai offers a vibrant lifestyle with a mix of modern high-rises and colonial architecture. Properties here range from luxury apartments to heritage buildings.",
  "Pune": "Known as the 'Oxford of the East', Pune is an educational and IT hub with pleasant weather year-round. The city offers a perfect blend of traditional and modern living spaces.",
  "Nagpur": "Located at the geographical center of India, Nagpur is known for its oranges and as the winter capital of Maharashtra. The city offers affordable housing options with good infrastructure.",
  "Thane": "A satellite city of Mumbai, Thane offers more spacious properties at relatively lower prices compared to Mumbai, with excellent connectivity to the main city.",
  "Nashik": "Famous for its vineyards and the Kumbh Mela, Nashik offers a peaceful living environment with growing real estate opportunities in both residential and commercial sectors.",
  "Aurangabad": "Known for its historical monuments including Ajanta and Ellora Caves, Aurangabad offers affordable housing with growing industrial areas.",
  "Solapur": "A major textile hub, Solapur offers affordable housing options with good connectivity to major cities in Maharashtra and neighboring states.",
  "Amravati": "Located in the Vidarbha region, Amravati is developing rapidly with new residential projects and improved infrastructure.",
  "Kolhapur": "Famous for its cuisine and Mahalaxmi Temple, Kolhapur offers traditional housing styles with modern amenities at reasonable prices.",
  "Navi Mumbai": "A planned satellite city of Mumbai, Navi Mumbai offers modern infrastructure, planned layouts, and relatively affordable housing compared to Mumbai.",
  "Sangli": "Known for its turmeric market, Sangli offers peaceful living with affordable housing options in both urban and semi-urban areas.",
  "Satara": "Located at the base of the Sahyadri mountain range, Satara offers scenic properties with a blend of rural charm and urban amenities.",
  "Latur": "A growing educational hub in Marathwada region, Latur offers affordable housing with improving infrastructure.",
  "Dhule": "Located in northern Maharashtra, Dhule offers affordable housing options with good connectivity to major cities.",
  "Ahmednagar": "Rich in history, Ahmednagar offers a mix of heritage properties and modern housing developments at reasonable prices.",
  "Akola": "A major cotton-producing center, Akola offers affordable housing with growing commercial opportunities.",
  "Jalgaon": "Known for banana cultivation, Jalgaon offers affordable housing with good educational institutions and growing industrial areas.",
  "Chandrapur": "Known for its coal mines and Tadoba National Park, Chandrapur offers affordable housing with growing industrial opportunities.",
  "Parbhani": "Located in the Marathwada region, Parbhani offers affordable housing with agricultural surroundings.",
  "Jalna": "An industrial city known for its steel and seed industries, Jalna offers affordable housing with growing commercial areas.",
  "Bhiwandi": "Known as the 'Manchester of India' for its textile industry, Bhiwandi offers affordable housing with proximity to Mumbai and Thane.",
  "Nanded": "Home to the famous Hazur Sahib Gurudwara, Nanded offers affordable housing with religious and cultural significance.",
  "Alibaug": "A coastal town and popular weekend getaway from Mumbai, Alibaug offers beachfront properties and vacation homes.",
  "Lonavala": "A hill station between Mumbai and Pune, Lonavala offers vacation homes and investment properties in a scenic environment.",
  "Mahabaleshwar": "A popular hill station, Mahabaleshwar offers premium vacation homes and investment properties with stunning valley views.",
  "Panchgani": "A scenic hill station known for its table land, Panchgani offers vacation homes in a peaceful environment.",
  "Matheran": "Asia's only automobile-free hill station, Matheran offers unique properties in an eco-friendly environment.",
  "Ratnagiri": "A coastal district known for Alphonso mangoes, Ratnagiri offers beachfront properties and agricultural land.",
  "Sindhudurg": "A coastal district with pristine beaches, Sindhudurg offers investment opportunities in tourism and hospitality sectors.",
  "Shirdi": "Famous for the Sai Baba Temple, Shirdi offers investment opportunities in hospitality and commercial properties catering to pilgrims."
}; 